//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongMassRename.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SongMassRename.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing artist to &quot;{0}&quot;.
        /// </summary>
        internal static string ChangingArtist {
            get {
                return ResourceManager.GetString("ChangingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing tag of &quot;{0}&quot;.
        /// </summary>
        internal static string ChangingTag {
            get {
                return ResourceManager.GetString("ChangingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing title to &quot;{0}&quot;.
        /// </summary>
        internal static string ChangingTitle {
            get {
                return ResourceManager.GetString("ChangingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of {0}.
        /// </summary>
        internal static string EndAction {
            get {
                return ResourceManager.GetString("EndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} files in the folder, which fit.
        /// </summary>
        internal static string FoundFiles {
            get {
                return ResourceManager.GetString("FoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading song &quot;{0}&quot;.
        /// </summary>
        internal static string LoadingSong {
            get {
                return ResourceManager.GetString("LoadingSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program end.
        /// </summary>
        internal static string ProgramEnd {
            get {
                return ResourceManager.GetString("ProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program start.
        /// </summary>
        internal static string ProgramStart {
            get {
                return ResourceManager.GetString("ProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving song as &quot;{0} - {1}&quot;.
        /// </summary>
        internal static string SavingSong {
            get {
                return ResourceManager.GetString("SavingSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}.
        /// </summary>
        internal static string StartingAction {
            get {
                return ResourceManager.GetString("StartingAction", resourceCulture);
            }
        }
    }
}
